variables:
  STAGING_URL: ''
  QC_URL: ''
  PRODUCTION_URL: ''
  GRUNT: grunt --gruntfile node_modules/@fishawack/config-grunt/Gruntfile.js
  BRANCH: --branch=$CI_COMMIT_REF_NAME

stages:
  - install
  - build
  - test
  - deploy
  - clean

install:
  stage: install
  script: 
    - npm run setup
  artifacts:
    expire_in: 2 hrs
    paths:
      - node_modules/
      - _Build/content/

build:
  stage: build
  script: $GRUNT dist $BRANCH
  artifacts:
    expire_in: 2 hrs
    paths:
      - _Output
      - _Build/media/generated/

test:
  stage: test
  script: xvfb-run npm test
  coverage: '/Code coverage: \d+\.\d+/'
  artifacts:
    expire_in: 2 hrs
    paths:
      - coverage/

pages:
  stage: deploy
  script:
    - mv coverage/report-html/ public/
    - mv _Build/media/generated/ public/badges/
  artifacts:
    expire_in: 2 hrs
    paths:
      - public

.deploy_template: &deploy_definition
  stage: deploy
  script: 
    - $GRUNT deploy $BRANCH
    - xvfb-run $GRUNT package $BRANCH
    - if [ ! -n "${SCHEDULED}" ]; then $GRUNT mail $BRANCH; fi
  retry: 2

deploy:staging:
  <<: *deploy_definition
  environment:
    name: staging
    url: $STAGING_URL
  only:
    - development

deploy:qc:
  <<: *deploy_definition
  environment:
    name: qc
    url: $QC_URL
  only:
    - qc

deploy:production:
  <<: *deploy_definition
  environment:
    name: production
    url: $PRODUCTION_URL
  only:
    - master

clean:
  stage: clean
  script:
    - git clean -xfd